### ISSUE TITLE
配置文件中可选项mcloud.pushPlusToken，注释掉会报错

### ISSUE THREAD

**Issue by gao4433** [alice1530/simple-mcloud-upload#3]

**Comment by gao4433** [comment]
https://github.com/alice1530/simple-mcloud-upload/blob/b6730b782b868de1cec766d47fc4372be8dac3c8/src/main/java/com/alice1530/mcloud/config/MCloudCronTask.java#L33


![image](https://github.com/alice1530/simple-mcloud-upload/assets/90138939/035f2fcd-e566-4e58-8706-5fbef1fea4fb)

**Comment by alice1530** [comment]
并不是啊，这个mcloud.token是中国移动云盘的token，微信推送的token才是mcloud.pushPlusToken，别搞混了

**Comment by alice1530** [comment]
> https://github.com/alice1530/simple-mcloud-upload/blob/b6730b782b868de1cec766d47fc4372be8dac3c8/src/main/java/com/alice1530/mcloud/config/MCloudCronTask.java#L33
> 
> ![image](https://user-images.githubusercontent.com/90138939/241718080-035f2fcd-e566-4e58-8706-5fbef1fea4fb.png)

mcloud.token是中国移动云盘的token，再这个文件里有被使用到。
src/main/java/com/alice1530/mcloud/config/MCloudProperties.java

**Comment by gao4433** [comment]
> 

这样啊，看来是我搞错了。配置里mcloud.pushPlusToken可以不写值或随便写一个值，我给注释掉所以报错了
![image](https://github.com/alice1530/simple-mcloud-upload/assets/90138939/4ba4d1bb-b458-484c-a855-5158e5c6e14f)
