### ISSUE TITLE
关于上传速度

### ISSUE THREAD

**Issue by gao4433** [alice1530/simple-mcloud-upload#4]
![image](https://github.com/alice1530/simple-mcloud-upload/assets/90138939/ab0ab022-a1c7-4d59-9f5c-86fc2ada73d2)
打扰问下大家上传速度都怎么样，为什么我一分钟只能上传10M不到的样子😢

**Comment by alice1530** [comment]
> ![image](https://user-images.githubusercontent.com/90138939/245144313-ab0ab022-a1c7-4d59-9f5c-86fc2ada73d2.png) 打扰问下大家上传速度都怎么样，为什么我一分钟只能上传10M不到的样子cry

你放在哪里上传？服务器吗？上传速度实际带宽为准。网速快慢瓶颈在于最小的带宽

**Comment by gao4433** [comment]
是的，想知道能不能自定义每次上传文件块大小，看了下好像是云盘那边处理的

**Comment by gao4433** [comment]
项目帮助很大👍👍👍，我是用在服务器aria2+ariang离线下载文件后自动上传到移动云盘，实现云盘离线下载和免流。奈何服务器带宽太低

**Comment by alice1530** [comment]
> 是的，想知道能不能自定义每次上传文件块大小，看了下好像是云盘那边处理的

分块大小在代码里写死了，按10M大小自动分块上传，要修改自己找一下，搜索1024应该等找到。

**Comment by gao4433** [comment]
好的，谢谢你！

**Comment by gao4433** [comment]
https://github.com/alice1530/simple-mcloud-upload/blob/b6730b782b868de1cec766d47fc4372be8dac3c8/src/main/java/com/alice1530/mcloud/store/MCloudClientService.java#LL50C53-L50C53
找到了
